### PR TITLE
Pin version of sopt

### PR DESCRIPTION
**Pull request by dpshelio**
This should fail till we release sopt 3.0.1
After releasing we can remove this restriction.

### CODE REVIEW

**Review by Luke-Pratley — APPROVED** [review]
Makes sense!

**Comment by Luke-Pratley** [comment]
@dpshelio The tests pass, which is a bit strange 😅

**Comment by Luke-Pratley** [comment]
@dpshelio Okay it doesn't fail in travis because we set it manually in the CMake here 
https://travis-ci.com/astro-informatics/purify/jobs/182169901#L397-L411

**Comment by dpshelio** [comment]
Phew! Yeah, that makes sense... Then we should also change the Travis version, to don't set up any as it's done inside the cmake files.

**Comment by dpshelio** [comment]
This should fail now as 3.0.1 doesn't exist.

**Pull request merged**
